export const SCHOOL_OPTIONS = [
  "ALL SCHOOLS",

  // ELEMENTARY
  "Isabela East Central Elementary School",
  "Isabela Bliss Elementary School",
  "Bishop Querexeta Elementary School",
  "Kaumpurnah Elementary School",
  "Simeon & Josefa Obsequio Elementary School",
  "Begang Central Elementary School",
  "Busay Elementary School",
  "Tabiawan Elementary School",
  "Latuan Elementary School",
  "Panunsulan Elementary School",
  "Kawa-Kawa Elementary School",
  "Look-Jambangan Elementary School",
  "Kauman Ekka Elementary School",
  "Palasanan Primary School",
  "Spillway Elementary School",
  "Kapatagan Diutay Elementary School",
  "Hadji Camlani Elementary School",
  "Calvario Peak Elementary School",
  "Calvario Elementary School",
  "Masola Elementary School",
  "Lanote Elementary School",
  "Lunot Elementary School",
  "Cabunbata Elementary School",
  "Isabela Central Pilot Elementary School",
  "Isabela Central Pilot Elementary School - Night",
  "Westside Elementary School",
  "Ustadz Wahab Akbar Elementary School",
  "Sunset Elementary School",
  "Ajibon Elementary School",
  "Sumagdang Elementary School",
  "Kumalarang Elementary School",
  "Menzi Elementary School",
  "Balatanay Elementary School",
  "Balawatin Elementary School",
  "Makiri Elementary School",
  "Campo Barn Elementary School",
  "Hadji Maulana Primary School",
  "Caro Elementary School",
  "Malamawi Central Elementary School",
  "Tampalan Elementary School",
  "Diki Elementary School",
  "Marang Marang Elementary School",
  "Lukbuton Elementary School",
  "Hadji Amilhamja Lahaba Memorial Elementary School",
  "MS Bernardo Elementary School",
  "Lampinigan Elementary School",
  "Ismael Integrated School",
  "Panigayan Integrated School",
  "Badjao Floating Integrated School",
  "Geras Integrated School",

  // HIGH SCHOOL
  "Basilan National High School",
  "Basilan National High School - Night",
  "Baluno National High School",
  "Malamawi National High School",
  "Begang National High School",
  "Isabela City National High School",
  "Kumalarang National High School",
  "Ismael Integrated School (High School)",
  "Lampinigan National High School",
  "Tandung Ahas National High School",
  "Panigayan Integrated School (High School)",
  "Badjao Floating Integrated School (High School)",
  "Geras Integrated School (High School)",
  "Caro National High School",
];